@startuml
skinparam ParticipantFontColor #FFFFFF

box processSolutionCommand() #ABCAFA
participant ":Parser" as Parser #FE2727
participant "questionListByTopic:QuestionsListByTopic" as QuestionsListByTopic #1162E3
participant "qnList:QuestionsList" as QuestionsList #1162E3
participant "topicList:TopicList" as TopicList #1162E3
participant "ui:Ui" as Ui #FE2727
end box

-> Parser:
activate Parser

Parser -> Parser : checkIfTwoParameters()
activate Parser
Parser --> Parser : hasTwoParameters
deactivate Parser

Parser -> TopicList
activate TopicList
TopicList -> TopicList : getSize()
activate TopicList
deactivate TopicList
TopicList --> Parser
deactivate TopicList

Parser -> Parser : getTopicOrQuestionNum()
activate Parser
Parser --> Parser : topicNum
deactivate Parser

Parser -> QuestionsListByTopic
activate QuestionsListByTopic
QuestionsListByTopic -> QuestionsListByTopic : getQuestionSet()
activate QuestionsListByTopic
deactivate QuestionsListByTopic

QuestionsListByTopic --> Parser : qnList
deactivate QuestionsListByTopic

Parser -> QuestionsList
activate QuestionsList
QuestionsList -> QuestionsList : getSize()
activate QuestionsList
deactivate QuestionsList
QuestionsList--> Parser
deactivate QuestionsList

Parser -> Parser : getTopicOrQuestionNum()
activate Parser
Parser --> Parser : questionNum
deactivate Parser

Parser -> TopicList
activate TopicList
TopicList -> TopicList : get()
activate TopicList
deactivate TopicList

TopicList -> TopicList : hasAttended()
activate TopicList
deactivate TopicList

TopicList --> Parser : hasAttempted
deactivate TopicList

opt (!hasAttempted)
    Parser -> Ui
    activate Ui

    Ui -> Ui: printNoSolutionAccess()
    activate Ui
    deactivate Ui

    Ui --> Parser
    deactivate Ui
end

alt (hasTwoParameters)
    Parser -> QuestionsList : get specific solution
    activate QuestionsList

    QuestionsList -> QuestionsList : getOneSolution()
    activate QuestionsList
    deactivate QuestionsList

    QuestionsList -> Ui
    activate Ui
    Ui -> Ui : printOneSolution()
    activate Ui
    deactivate Ui
    Ui --> QuestionsList
    deactivate Ui
    QuestionsList --> Parser
    deactivate QuestionsList
else
    Parser -> QuestionsList : get all solutions
    activate QuestionsList

    QuestionsList -> QuestionsList : getAllSolutions()
    activate QuestionsList
    deactivate QuestionsList

    QuestionsList -> Ui
    activate Ui
    Ui -> Ui : printAllSolutions()
    activate Ui
    deactivate Ui
    Ui --> QuestionsList :
    deactivate Ui
    QuestionsList --> Parser
    deactivate QuestionsList
end

@enduml
