@startuml

left to right direction
top to bottom direction

package "Program Starts" as AnyUserCommands {
    actor User
    (display results)
    (display solution)
    (exit)
    (display help)
    (display list) -[hidden]- User
    (display explanation)
}

package "Step 1: GameSetUp" as SetUp {
    (timed mode)
    (choose topic)
}
package "Step 2: GamePlay" as GamePlay {
    (answering questions)
}

User --> SetUp
SetUp --> GamePlay

@enduml